template: |
  ## Changelog
  $CHANGES

name-template: 'Release v$DATE_VERSION'
tag-template: 'v$DATE_VERSION'
categories:
  - title: New Features 🎉
    labels:
      - enhancement
  - title: Bug Fixes 🐛
    labels:
      - bug
  - title: Documentation 📚
    labels:
      - documentation
  - title: Other Changes
    labels:
      - '*'
change-template: '- $TITLE (#$NUMBER) @${AUTHOR}'
no-changes-template: '- No changes'

# Version format: v<Year>.<Month>.<Patch>
version-template: 'v$YEAR.$MONTH.$PATCH'

version-resolver:
  major: { labels: [] }
  minor: { labels: [] }
  patch: { labels: [] }
  default: 'patch'

# Optional: Increment the patch version automatically
increment-version: true
