name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: go mod download
          
      - name: Test with the Go CLI
        run: go test ./...

      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from versions.txt
        id: version
        run: |
          # Extract version from versions.txt (after 'VERSION: ')
          VERSION=$(grep -oP '(?<=VERSION: )v\d+\.\d+\.\d+' version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"

      - name: Build Docker image with extracted version
        run: |
          docker build -t manisankardivi/new:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push manisankardivi/new:${{ env.VERSION }}

  deploy:
    runs-on: self-hosted
    needs: build_and_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
      
      - name: Replace image version in Kubernetes manifest
        run: |
          # Replace image version placeholder in Kubernetes manifest
          sed -i "s|\(image: your-dockerhub-username/myapp:\).*|\\1${{ env.VERSION }}|" manifest.yaml

      - name: Apply updated Kubernetes manifest
        run: |
          kubectl apply -f manifest.yaml

      - name: Verify Kubernetes resources
        run: kubectl get all -A
