name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: go mod download
          
      - name: Test with the Go CLI
        run: go test ./...

      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from VERSION file
        id: version_step
        run: |
          # Read the entire content of the VERSION file and trim any surrounding whitespace
          VERSION=$(cat VERSION | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version extracted: $VERSION"
      

      - name: Build Docker image with extracted version
        run: |
          docker build -t manisankardivi/new:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push manisankardivi/new:${{ env.VERSION }}


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Verify Kubernetes Manifests
        run: ls -la
  
      - name: Load VERSION
        id: load_version
        run: |
          VERSION=$(cat VERSION | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Loaded VERSION: $VERSION"
  
      - name: Update Image Version in Manifest
        run: |
          sed -i "s|image: manisankardivi/new:.*|image: manisankardivi/new:$VERSION|" manifest.yaml
          echo "Updated manifest.yaml with image tag: $VERSION"
  
      - name: Set up kubeconfig
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config
  
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl
  
      - name: Deploy to Kubernetes
        run: |
          # Example kubectl command, replace with your deployment command
          kubectl apply -f manifest.yaml  # adjust based on your manifest files
  
      - name: Verify Deployment
        run: |
          kubectl get pods -o wide
          
              
