name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      # Step 5: Build the application
      - name: Build the application
        run: go build -o artifact main.go

          
      - name: List files
        run: pwd && ls -lh 
