name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: |
          go mod download
          
      - name: Test with the Go CLI
        run: go test
        
      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build an image from Dockerfile
        run: | 
          docker build -t manisankardivi/go-app:v1 .
          docker images
          docker ps 
          docker ps -a

      # - name: Set up Trivy
      #   uses: aquasecurity/trivy-action@0.28.0  # Use the Trivy action to set up Trivy
      #   with:
      #     version: v0.56.1  # Specify the Trivy version you want
  
      # - name: Scan Image
      #   run: |
      #     trivy image --severity HIGH,CRITICAL --format table --exit-code 1 manisankar/go-app:v1
      - name: Docker push to Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: manisankardivi/go-app:v1
