name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Create Build Directory
        run: mkdir -p build  # Create 'build' directory for the output

      - name: Build Go Application
        run: go build -o build/app ./main.go  # Build binary and place it in 'build' directory

      - name: List Files After Build
        run: |
          pwd
          ls -la build  # List files in the 'build' directory

      - name: Run Tests
        run: go test ./...

      - name: Upload Code Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-binary
          path: build/app  # Upload binary from 'build' directory
