name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  build-code:
    name: Build Code
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2  # Change to your Go version
        

      - name: Go Mod Download
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we're in the workspace directory
          go mod download
        
      - name: Build Go Application
        run: |
          cd $GITHUB_WORKSPACE  # Ensure we're in the workspace directory
          go build -o app ./main.go
        
      - name: Upload Code Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-binary
          path: ./app
