name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  build-code:
    name: Build Code
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2  # Change to your Go version
          
      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download
          
      - name: Build Go Application
        run: |
          go build -o app ./main.go
          
      - name: Run Tests
        run: |
          go test ./...  # Run all tests in the module

      - name: Upload Code Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-binary
          path: ./app
