name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-cd:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2  # Change to your Go version

      - name: Build, Test, and Install Dependencies
        run: |
          pwd
          ls -la
          go mod tidy
          go build -o app ./main.go
          go test ./...

      - name: Check for dist directory and upload artifacts
        if: success() # Only run if previous steps were successful
        run: |
          if [ -d "dist" ]; then
            echo "Uploading artifacts from dist directory..."
            echo "This will upload all files except markdown files."
            echo "Note: Use actions/upload-artifact to upload your artifacts."
          else
            echo "No dist directory found. Skipping artifact upload."
          fi

      - name: Upload Code Artifact
        if: success() && startsWith(steps.check-for-dist.outputs.message, 'Uploading artifacts')
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
