name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: go mod download
          
      - name: Test with the Go CLI
        run: go test ./...

      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn
      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          VERSION=$(git rev-parse --short HEAD)  # Get short commit hash for unique tagging
          docker build -t manisankardivi/go-sha:latest -t manisankardivi/go-sha:$VERSION .  # Build image with 'latest' and commit hash tags
          docker images  # Verify the built image

      # Step 4: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Store your Docker Hub username as a secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Store your Docker Hub token as a secret

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          VERSION=$(git rev-parse --short HEAD)  # Get commit hash again for tagging
          docker push manisankardivi/go-sha:latest  # Push 'latest' tag
          docker push manisankardivi/go-sha:$VERSION  # Push commit hash tag
          
      # Step 6: Verify Docker images pushed
      - name: Verify Docker images
        run: |
          docker images  # Verify the images pushed to Docker Hub
          docker ps -a  # List all containers

      
  deploy:
    runs-on: self-hosted  
    needs: build_and_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
      
      - name: Check manifest files
        run: ls -la

      - name: Verify Kubernetes resources
        run: kubectl get all -A
