# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  build-code:
    name: Build Code
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23  # Change to your Go version
      - name: Build Go Application
        run: |
          go build -o app ./main.go
      - name: Upload Code Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: ./app
