name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: go mod download
          
      - name: Test with the Go CLI
        run: go test ./...

      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from VERSION file
        id: version_step
        run: |
          VERSION=$(cat VERSION | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        outputs:
          version: ${{ steps.version_step.outputs.VERSION }}

      - name: Build Docker image with extracted version
        run: docker build -t manisankardivi/new:${{ steps.version_step.outputs.version }} .

      - name: Push Docker image
        run: docker push manisankardivi/new:${{ steps.version_step.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_scan
    steps:
      - name: Checkout k8s-repo
        uses: actions/checkout@v4
        with:
          repository: manisankar-divi/k8s-repo
          path: k8s-repo

      - name: Update K8S Manifest & Push to Repo
        run: |
          cd k8s-repo

          # Use the version from the previous job
          VERSION="${{ needs.build_and_scan.outputs.version }}"
          echo "Updating manifest.yaml with version $VERSION"

          # Update the manifest file
          sed -i "s|image: manisankardivi/new:.*|image: manisankardivi/new:$VERSION|" manifest.yaml

          # Configure Git
          git config --global user.email "manisankar-divi@gmail.com"
          git config --global user.name "manisankar-divi"

          # Commit and push changes
          git add manifest.yaml
          git commit -m "Updated manifest.yaml with version $VERSION | GitHub Actions Pipeline"
          git push origin main
