name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: |
          go get .
          go get -u golang.org/x/lint/golint
          go vet .
    
      - name: Test with the Go CLI
        run: go test
        
      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
          docker images && docker ps && docker ps -a
          pwd & ls -la

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'                     # Set output format to table
          output: '/tmp/trivy-report.txt'     # Save report as text
          exit-code: '1'                      # Fail on critical vulnerabilities
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: /tmp/trivy-report.txt          # Upload the table report
          if-no-files-found: warn

      - name: Display Trivy report
        run: |
          cat /tmp/trivy-report.txt         

