name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: |
          go get .
          go get -u golang.org/x/lint/golint
          go vet .
          golint .
        
      - name: Build
        run: go build -v ./...
        
      - name: Test with the Go CLI
        run: go test
        
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
                  
      - name: Build the application
        run: go build -o artifact main.go
          
      - name: List files
        run: pwd && ls -lh 
