name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: go mod download
          
      - name: Test with the Go CLI
        run: go test ./...

      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # Get the short commit hash for unique tagging
          VERSION=$(git rev-parse --short HEAD)  # Short commit hash
          docker build -t myapp:latest -t myapp:$VERSION .  # Build image with latest and commit hash tags

      - name: Push Docker image
        run: |
          VERSION=$(git rev-parse --short HEAD)  # Get commit hash again for tagging
          docker push myapp:latest  # Push 'latest' tag
          docker push myapp:$VERSION  # Push commit hash tag
          
      - name: Verify Docker images
        run: |
          docker images  # Verify images pushed to Docker Hub
          docker ps -a  # List all containers

  deploy:
    runs-on: self-hosted  
    needs: build_and_scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods
      
      - name: Check manifest files
        run: ls -la

      - name: Verify Kubernetes resources
        run: kubectl get all -A
