name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      
      - name: Install dependencies
        run: |
          go get .
          go get -u golang.org/x/lint/golint
          go vet .
    
      - name: Test with the Go CLI
        run: go test
        
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/*.sum
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: |
            Linux-build-
          
      - name: Build the application
        run: |
          mkdir -p dist
          go build -o dist/main ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: dist
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
          
      - name: List files
        run: pwd && ls -lh 

      # Docker Build Steps
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t docker.io/manisankardivi/my-go-app:${{ github.sha }} .
          docker images
          docker ps 
          docker ps -a

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/manisankardivi/my-go-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          run: |
            trivy image ${{'docker.io/manisankardivi/my-go-app:${{ github.sha }}'}}

      - name: Push Docker image
        if: success()
        run: docker push docker.io/manisankardivi/my-go-app:${{ github.sha }}
